#ifndef PROCESSING_H
#define PROCESSING_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PROCESSING_ATTR_FORMAT_FLOAT 1

#define PROCESSING_ATTR_FORMAT_FLOAT2 2

#define PROCESSING_ATTR_FORMAT_FLOAT3 3

#define PROCESSING_ATTR_FORMAT_FLOAT4 4

#define PROCESSING_TOPOLOGY_POINT_LIST 0

#define PROCESSING_TOPOLOGY_LINE_LIST 1

#define PROCESSING_TOPOLOGY_LINE_STRIP 2

#define PROCESSING_TOPOLOGY_TRIANGLE_LIST 3

#define PROCESSING_TOPOLOGY_TRIANGLE_STRIP 4

#define PROCESSING_STROKE_CAP_ROUND 0

#define PROCESSING_STROKE_CAP_SQUARE 1

#define PROCESSING_STROKE_CAP_PROJECT 2

#define PROCESSING_STROKE_JOIN_ROUND 0

#define PROCESSING_STROKE_JOIN_MITER 1

#define PROCESSING_STROKE_JOIN_BEVEL 2

#define PROCESSING_BLEND_MODE_BLEND 0

#define PROCESSING_BLEND_MODE_ADD 1

#define PROCESSING_BLEND_MODE_SUBTRACT 2

#define PROCESSING_BLEND_MODE_DARKEST 3

#define PROCESSING_BLEND_MODE_LIGHTEST 4

#define PROCESSING_BLEND_MODE_DIFFERENCE 5

#define PROCESSING_BLEND_MODE_EXCLUSION 6

#define PROCESSING_BLEND_MODE_MULTIPLY 7

#define PROCESSING_BLEND_MODE_SCREEN 8

#define PROCESSING_BLEND_MODE_REPLACE 9

#define PROCESSING_BLEND_FACTOR_ZERO 0

#define PROCESSING_BLEND_FACTOR_ONE 1

#define PROCESSING_BLEND_FACTOR_SRC 2

#define PROCESSING_BLEND_FACTOR_ONE_MINUS_SRC 3

#define PROCESSING_BLEND_FACTOR_SRC_ALPHA 4

#define PROCESSING_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA 5

#define PROCESSING_BLEND_FACTOR_DST 6

#define PROCESSING_BLEND_FACTOR_ONE_MINUS_DST 7

#define PROCESSING_BLEND_FACTOR_DST_ALPHA 8

#define PROCESSING_BLEND_FACTOR_ONE_MINUS_DST_ALPHA 9

#define PROCESSING_BLEND_FACTOR_SRC_ALPHA_SATURATED 10

#define PROCESSING_BLEND_OP_ADD 0

#define PROCESSING_BLEND_OP_SUBTRACT 1

#define PROCESSING_BLEND_OP_REVERSE_SUBTRACT 2

#define PROCESSING_BLEND_OP_MIN 3

#define PROCESSING_BLEND_OP_MAX 4

#define PROCESSING_MOUSE_LEFT 0

#define PROCESSING_MOUSE_MIDDLE 1

#define PROCESSING_MOUSE_RIGHT 2

#define PROCESSING_KEY_SPACE 32

#define PROCESSING_KEY_QUOTE 39

#define PROCESSING_KEY_COMMA 44

#define PROCESSING_KEY_MINUS 45

#define PROCESSING_KEY_PERIOD 46

#define PROCESSING_KEY_SLASH 47

#define PROCESSING_KEY_0 48

#define PROCESSING_KEY_1 49

#define PROCESSING_KEY_2 50

#define PROCESSING_KEY_3 51

#define PROCESSING_KEY_4 52

#define PROCESSING_KEY_5 53

#define PROCESSING_KEY_6 54

#define PROCESSING_KEY_7 55

#define PROCESSING_KEY_8 56

#define PROCESSING_KEY_9 57

#define PROCESSING_KEY_SEMICOLON 59

#define PROCESSING_KEY_EQUAL 61

#define PROCESSING_KEY_A 65

#define PROCESSING_KEY_B 66

#define PROCESSING_KEY_C 67

#define PROCESSING_KEY_D 68

#define PROCESSING_KEY_E 69

#define PROCESSING_KEY_F 70

#define PROCESSING_KEY_G 71

#define PROCESSING_KEY_H 72

#define PROCESSING_KEY_I 73

#define PROCESSING_KEY_J 74

#define PROCESSING_KEY_K 75

#define PROCESSING_KEY_L 76

#define PROCESSING_KEY_M 77

#define PROCESSING_KEY_N 78

#define PROCESSING_KEY_O 79

#define PROCESSING_KEY_P 80

#define PROCESSING_KEY_Q 81

#define PROCESSING_KEY_R 82

#define PROCESSING_KEY_S 83

#define PROCESSING_KEY_T 84

#define PROCESSING_KEY_U 85

#define PROCESSING_KEY_V 86

#define PROCESSING_KEY_W 87

#define PROCESSING_KEY_X 88

#define PROCESSING_KEY_Y 89

#define PROCESSING_KEY_Z 90

#define PROCESSING_KEY_BRACKET_LEFT 91

#define PROCESSING_KEY_BACKSLASH 92

#define PROCESSING_KEY_BRACKET_RIGHT 93

#define PROCESSING_KEY_BACKQUOTE 96

#define PROCESSING_KEY_ESCAPE 256

#define PROCESSING_KEY_ENTER 257

#define PROCESSING_KEY_TAB 258

#define PROCESSING_KEY_BACKSPACE 259

#define PROCESSING_KEY_INSERT 260

#define PROCESSING_KEY_DELETE 261

#define PROCESSING_KEY_RIGHT 262

#define PROCESSING_KEY_LEFT 263

#define PROCESSING_KEY_DOWN 264

#define PROCESSING_KEY_UP 265

#define PROCESSING_KEY_PAGE_UP 266

#define PROCESSING_KEY_PAGE_DOWN 267

#define PROCESSING_KEY_HOME 268

#define PROCESSING_KEY_END 269

#define PROCESSING_KEY_CAPS_LOCK 280

#define PROCESSING_KEY_SCROLL_LOCK 281

#define PROCESSING_KEY_NUM_LOCK 282

#define PROCESSING_KEY_PRINT_SCREEN 283

#define PROCESSING_KEY_PAUSE 284

#define PROCESSING_KEY_F1 290

#define PROCESSING_KEY_F2 291

#define PROCESSING_KEY_F3 292

#define PROCESSING_KEY_F4 293

#define PROCESSING_KEY_F5 294

#define PROCESSING_KEY_F6 295

#define PROCESSING_KEY_F7 296

#define PROCESSING_KEY_F8 297

#define PROCESSING_KEY_F9 298

#define PROCESSING_KEY_F10 299

#define PROCESSING_KEY_F11 300

#define PROCESSING_KEY_F12 301

#define PROCESSING_KEY_NUMPAD_0 320

#define PROCESSING_KEY_NUMPAD_1 321

#define PROCESSING_KEY_NUMPAD_2 322

#define PROCESSING_KEY_NUMPAD_3 323

#define PROCESSING_KEY_NUMPAD_4 324

#define PROCESSING_KEY_NUMPAD_5 325

#define PROCESSING_KEY_NUMPAD_6 326

#define PROCESSING_KEY_NUMPAD_7 327

#define PROCESSING_KEY_NUMPAD_8 328

#define PROCESSING_KEY_NUMPAD_9 329

#define PROCESSING_KEY_NUMPAD_DECIMAL 330

#define PROCESSING_KEY_NUMPAD_DIVIDE 331

#define PROCESSING_KEY_NUMPAD_MULTIPLY 332

#define PROCESSING_KEY_NUMPAD_SUBTRACT 333

#define PROCESSING_KEY_NUMPAD_ADD 334

#define PROCESSING_KEY_NUMPAD_ENTER 335

#define PROCESSING_KEY_NUMPAD_EQUAL 336

#define PROCESSING_KEY_SHIFT_LEFT 340

#define PROCESSING_KEY_CONTROL_LEFT 341

#define PROCESSING_KEY_ALT_LEFT 342

#define PROCESSING_KEY_SUPER_LEFT 343

#define PROCESSING_KEY_SHIFT_RIGHT 344

#define PROCESSING_KEY_CONTROL_RIGHT 345

#define PROCESSING_KEY_ALT_RIGHT 346

#define PROCESSING_KEY_SUPER_RIGHT 347

#define PROCESSING_KEY_CONTEXT_MENU 348

#define PROCESSING_CURSOR_ARROW 0

#define PROCESSING_CURSOR_CROSS 1

#define PROCESSING_CURSOR_HAND 2

#define PROCESSING_CURSOR_MOVE 3

#define PROCESSING_CURSOR_TEXT 4

#define PROCESSING_CURSOR_WAIT 5

// A color with 4 float components and its color space.
typedef struct Color {
  float c1;
  float c2;
  float c3;
  float a;
  uint8_t space;
} Color;

// A column-major 4x4 matrix.
typedef struct Matrix {
  float m[16];
} Matrix;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initialize libProcessing.
//
// SAFETY:
// - This is called from the main thread if the platform requires it.
// - This can only be called once.
void processing_init(void);

// Create a WebGPU surface from a macOS NSWindow handle.
//
// SAFETY:
// - Init has been called.
// - window_handle is a valid NSWindow pointer.
// - This is called from the same thread as init.
uint64_t processing_surface_create(uint64_t window_handle,
                                   uint64_t _display_handle,
                                   uint32_t width,
                                   uint32_t height,
                                   float scale_factor);

// Create a WebGPU surface from a Windows HWND handle.
//
// SAFETY:
// - Init has been called.
// - window_handle is a valid HWND.
// - This is called from the same thread as init.
uint64_t processing_surface_create(uint64_t window_handle,
                                   uint64_t _display_handle,
                                   uint32_t width,
                                   uint32_t height,
                                   float scale_factor);

// Create a WebGPU surface from a Wayland window and display handle.
//
// SAFETY:
// - Init has been called.
// - window_handle is a valid wl_surface pointer.
// - display_handle is a valid wl_display pointer.
// - This is called from the same thread as init.
uint64_t processing_surface_create_wayland(uint64_t window_handle,
                                           uint64_t display_handle,
                                           uint32_t width,
                                           uint32_t height,
                                           float scale_factor);

// Create a WebGPU surface from an X11 window and display handle.
//
// SAFETY:
// - Init has been called.
// - window_handle is a valid X11 Window ID.
// - display_handle is a valid X11 Display pointer.
// - This is called from the same thread as init.
uint64_t processing_surface_create_x11(uint64_t window_handle,
                                       uint64_t display_handle,
                                       uint32_t width,
                                       uint32_t height,
                                       float scale_factor);

// Create a WebGPU surface on Linux. The display server is auto-detected from
// the environment.
//
// SAFETY:
// - Init has been called.
// - The handle types match the active display server.
// - This is called from the same thread as init.
uint64_t processing_surface_create(uint64_t window_handle,
                                   uint64_t display_handle,
                                   uint32_t width,
                                   uint32_t height,
                                   float scale_factor);

// Create a graphics context for a surface.
//
// SAFETY:
// - Init and surface_create have been called.
// - surface_id is a valid ID returned from surface_create.
// - This is called from the same thread as init.
uint64_t processing_graphics_create(uint64_t surface_id, uint32_t width, uint32_t height);

// Configure before begin_draw/command recording. 0=Default (4 samples), 1=Off.
// Invalid values and late changes set processing's existing error state.
void processing_graphics_set_antialiasing(uint64_t graphics_id, uint8_t mode);

// Configure before first draw. 0=inherit image, 1=Linear, 2=Nearest.
void processing_graphics_set_image_sampling(uint64_t graphics_id, uint8_t mode);

// Atomic Off + Nearest, before the first user draw.
void processing_graphics_no_smooth(uint64_t graphics_id);

// Destroy a graphics context.
//
// SAFETY:
// - Init and graphics_create have been called.
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_graphics_destroy(uint64_t graphics_id);

// Destroy the surface associated with the given window ID.
//
// SAFETY:
// - Init and surface_create have been called.
// - window_id is a valid ID returned from surface_create.
// - This is called from the same thread as init.
void processing_surface_destroy(uint64_t window_id);

// Update window size when resized.
//
// SAFETY:
// - Init and surface_create have been called.
// - window_id is a valid ID returned from surface_create.
// - This is called from the same thread as init.
void processing_surface_resize(uint64_t window_id, uint32_t width, uint32_t height);

// Set the background color for the given graphics context.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_background_color(uint64_t graphics_id, struct Color color);

// Set the background image for the given graphics context.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - image_id is a valid ID returned from processing_image_create.
// - The image has been fully uploaded.
// - This is called from the same thread as init.
void processing_background_image(uint64_t graphics_id, uint64_t image_id);

// Clear the graphics surface to transparent.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_clear(uint64_t graphics_id);

// Begins the draw for the given graphics context.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_begin_draw(uint64_t graphics_id);

// Flushes recorded draw commands for the given graphics context.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_flush(uint64_t graphics_id);

// Ends the draw for the given graphics context and presents the frame.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - Init has been called and exit has not been called.
// - This is called from the same thread as init.
void processing_end_draw(uint64_t graphics_id);

// Shuts down internal resources with given exit code, but does *not* terminate the process.
//
// SAFETY:
// - This is called from the same thread as init.
// - Caller ensures that update is never called again after exit.
void processing_exit(uint8_t exit_code);

// Set the color mode for a graphics context.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_color_mode(uint64_t graphics_id,
                           uint8_t space,
                           float max1,
                           float max2,
                           float max3,
                           float max_alpha);

// Set the fill color.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_set_fill(uint64_t graphics_id, struct Color color);

// Set the stroke color.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_set_stroke_color(uint64_t graphics_id, struct Color color);

// Set the stroke weight.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_set_stroke_weight(uint64_t graphics_id, float weight);

// Set the stroke cap mode.
void processing_set_stroke_cap(uint64_t graphics_id, uint8_t cap);

// Set the stroke join mode.
void processing_set_stroke_join(uint64_t graphics_id, uint8_t join);

// Set the rect mode.
void processing_rect_mode(uint64_t graphics_id, uint8_t mode);

// Set the ellipse mode.
void processing_ellipse_mode(uint64_t graphics_id, uint8_t mode);

// Disable fill for subsequent shapes.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_no_fill(uint64_t graphics_id);

// Disable stroke for subsequent shapes.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_no_stroke(uint64_t graphics_id);

// Push the current transformation matrix onto the stack.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_push_matrix(uint64_t graphics_id);

// Pop the transformation matrix from the stack.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_pop_matrix(uint64_t graphics_id);

// Push the current style onto the style stack.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_push_style(uint64_t graphics_id);

// Pop the most recently saved style off the style stack.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_pop_style(uint64_t graphics_id);

// Push both the style and the transformation matrix onto their stacks.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_push(uint64_t graphics_id);

// Pop both the style and the transformation matrix off their stacks.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_pop(uint64_t graphics_id);

// Reset the transformation matrix to identity.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_reset_matrix(uint64_t graphics_id);

// Translate the coordinate system.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_translate(uint64_t graphics_id, float x, float y, float z);

// Rotate the coordinate system by `angle` about the axis (x, y, z).
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_rotate(uint64_t graphics_id, float angle, float x, float y, float z);

// Scale the coordinate system.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_scale(uint64_t graphics_id, float x, float y, float z);

// Shear along the X axis.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_shear_x(uint64_t graphics_id, float angle);

// Shear along the Y axis.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_shear_y(uint64_t graphics_id, float angle);

void processing_set_blend_mode(uint64_t graphics_id, uint8_t mode);

void processing_set_custom_blend_mode(uint64_t graphics_id,
                                      uint8_t color_src,
                                      uint8_t color_dst,
                                      uint8_t color_op,
                                      uint8_t alpha_src,
                                      uint8_t alpha_dst,
                                      uint8_t alpha_op);

// Draw a rectangle.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_rect(uint64_t graphics_id,
                     float x,
                     float y,
                     float w,
                     float h,
                     float tl,
                     float tr,
                     float br,
                     float bl);

// Draw an ellipse.
void processing_ellipse(uint64_t graphics_id, float cx, float cy, float w, float h);

// Draw a circle.
void processing_circle(uint64_t graphics_id, float cx, float cy, float d);

// Draw a line.
void processing_line(uint64_t graphics_id, float x1, float y1, float x2, float y2);

// Draw a triangle.
void processing_triangle(uint64_t graphics_id,
                         float x1,
                         float y1,
                         float x2,
                         float y2,
                         float x3,
                         float y3);

// Draw a quadrilateral.
void processing_quad(uint64_t graphics_id,
                     float x1,
                     float y1,
                     float x2,
                     float y2,
                     float x3,
                     float y3,
                     float x4,
                     float y4);

// Draw a point.
void processing_point(uint64_t graphics_id, float x, float y);

// Draw a square.
void processing_square(uint64_t graphics_id, float x, float y, float s);

// Draw an arc.
void processing_arc(uint64_t graphics_id,
                    float cx,
                    float cy,
                    float w,
                    float h,
                    float start,
                    float stop,
                    uint8_t mode);

// Draw a cubic bezier curve.
void processing_bezier(uint64_t graphics_id,
                       float x1,
                       float y1,
                       float x2,
                       float y2,
                       float x3,
                       float y3,
                       float x4,
                       float y4);

// Draw a Catmull-Rom curve.
void processing_curve(uint64_t graphics_id,
                      float x1,
                      float y1,
                      float x2,
                      float y2,
                      float x3,
                      float y3,
                      float x4,
                      float y4);

// Draw a cylinder.
void processing_cylinder(uint64_t graphics_id, float radius, float height, uint32_t detail);

// Draw a cone.
void processing_cone(uint64_t graphics_id, float radius, float height, uint32_t detail);

// Draw a torus.
void processing_torus(uint64_t graphics_id,
                      float radius,
                      float tube_radius,
                      uint32_t major_segments,
                      uint32_t minor_segments);

// Draw a plane.
void processing_plane(uint64_t graphics_id, float width, float height);

// Draw a capsule.
void processing_capsule(uint64_t graphics_id, float radius, float length, uint32_t detail);

// Draw a conical frustum.
void processing_conical_frustum(uint64_t graphics_id,
                                float radius_top,
                                float radius_bottom,
                                float height,
                                uint32_t detail);

// Draw a tetrahedron.
void processing_tetrahedron(uint64_t graphics_id, float radius);

// Begin recording vertices for a custom shape.
void processing_begin_shape(uint64_t graphics_id, uint8_t kind);

// End recording vertices and draw the shape.
void processing_end_shape(uint64_t graphics_id, bool close);

// Add a vertex to the current shape.
void processing_vertex(uint64_t graphics_id, float x, float y);

// Add a cubic bezier vertex to the current shape.
void processing_bezier_vertex(uint64_t graphics_id,
                              float cx1,
                              float cy1,
                              float cx2,
                              float cy2,
                              float x,
                              float y);

// Add a quadratic bezier vertex to the current shape.
void processing_quadratic_vertex(uint64_t graphics_id, float cx, float cy, float x, float y);

// Add a Catmull-Rom curve vertex to the current shape.
void processing_curve_vertex(uint64_t graphics_id, float x, float y);

// Begin a contour within the current shape.
void processing_begin_contour(uint64_t graphics_id);

// End the current contour.
void processing_end_contour(uint64_t graphics_id);

// Load a font file and return a font entity ID.
// Returns 0 on error.
//
// # Safety
// - path_ptr is a valid pointer to a null-terminated string.
uint64_t processing_load_font(const char *path_ptr);

// Create a font handle from an existing font family name.
// Returns 0 on error.
//
// # Safety
// - name_ptr is a valid pointer to a null-terminated string.
uint64_t processing_create_font(const char *name_ptr);

// Query the number of variable font axes for a font.
// Returns 0 if the font is not variable or not found.
uint32_t processing_font_variation_count(uint64_t font_id);

// Query variable font axis info.
// Writes tag (4 bytes), min, max, default to out buffer at the given index.
//
// # Safety
// - out_tag is a valid pointer to at least 4 writable bytes.
// - out_min, out_max, out_default are valid pointers to writable f32 values.
bool processing_font_variation(uint64_t font_id,
                               uint32_t index,
                               uint8_t *out_tag,
                               float *out_min,
                               float *out_max,
                               float *out_default);

// Set the current text font.
// Pass 0 to reset to the default font.
void processing_text_font(uint64_t graphics_id, uint64_t font_id);

// Draw text at a position.
//
// # Safety
// - str_ptr is a valid pointer to a null-terminated string.
void processing_text(uint64_t graphics_id, const char *str_ptr, float x, float y);

// Draw text at a 3D position.
//
// # Safety
// - str_ptr is a valid pointer to a null-terminated string.
void processing_text_3d(uint64_t graphics_id, const char *str_ptr, float x, float y, float z);

// Draw an integer as text at a position.
void processing_text_int(uint64_t graphics_id, int32_t value, float x, float y);

// Draw a float as text at a position (formatted to 3 decimal places).
void processing_text_float(uint64_t graphics_id, float value, float x, float y);

// Draw text within a bounding box (with word wrapping).
//
// # Safety
// - str_ptr is a valid pointer to a null-terminated string.
void processing_text_box(uint64_t graphics_id,
                         const char *str_ptr,
                         float x,
                         float y,
                         float w,
                         float h);

// Set the text style. 0=NORMAL, 1=ITALIC, 2=BOLD, 3=BOLDITALIC
void processing_text_style(uint64_t graphics_id, uint8_t style);

// Compute the bounding box of text. Writes [x, y, w, h] to out_bounds.
//
// # Safety
// - str_ptr is a valid pointer to a null-terminated string.
// - out_bounds is a valid pointer to a writable float array of at least 4 elements.
void processing_text_bounds(uint64_t graphics_id,
                            const char *str_ptr,
                            float x,
                            float y,
                            float *out_bounds);

// Set a font variation axis value (e.g. "wdth", 75.0).
//
// # Safety
// - tag_ptr is a valid pointer to a null-terminated string.
void processing_text_variation(uint64_t graphics_id, const char *tag_ptr, float value);

// Clear all font variation axis overrides.
void processing_clear_text_variations(uint64_t graphics_id);

// Enable/configure an OpenType font feature (e.g. "smcp", 1).
//
// # Safety
// - tag_ptr is a valid pointer to a null-terminated string.
void processing_text_feature(uint64_t graphics_id, const char *tag_ptr, uint16_t value);

// Disable an OpenType font feature.
//
// # Safety
// - tag_ptr is a valid pointer to a null-terminated string.
void processing_no_text_feature(uint64_t graphics_id, const char *tag_ptr);

// Clear all OpenType font feature overrides.
void processing_clear_text_features(uint64_t graphics_id);

// Set per-glyph colors for the next text() call.
// colors_ptr points to an array of (r, g, b, a) float tuples.
//
// # Safety
// - colors_ptr is a valid pointer to count * 4 readable floats.
void processing_text_glyph_colors(uint64_t graphics_id, const float *colors_ptr, uint32_t count);

// Set the font weight for variable fonts (e.g. 100-900).
void processing_text_weight(uint64_t graphics_id, float weight);

// Set the text size.
void processing_text_size(uint64_t graphics_id, float size);

// Set the text alignment.
// h: 0=LEFT, 1=CENTER, 2=RIGHT
// v: 0=BASELINE, 1=TOP, 2=CENTER, 3=BOTTOM
void processing_text_align(uint64_t graphics_id, uint8_t h, uint8_t v);

// Set the text leading (line spacing).
void processing_text_leading(uint64_t graphics_id, float leading);

// Set the text wrap mode. 0=WORD, 1=CHAR
void processing_text_wrap(uint64_t graphics_id, uint8_t mode);

// Measure the width of text.
//
// # Safety
// - str_ptr is a valid pointer to a null-terminated string.
float processing_text_width(uint64_t graphics_id, const char *str_ptr);

// Get the text ascent for the current font size.
float processing_text_ascent(uint64_t graphics_id);

// Get the text descent for the current font size.
float processing_text_descent(uint64_t graphics_id);

// Create an image from raw pixel data.
//
// # Safety
// - Init has been called.
// - data is a valid pointer to data_len bytes of RGBA pixel data.
// - This is called from the same thread as init.
uint64_t processing_image_create(uint32_t width,
                                 uint32_t height,
                                 const uint8_t *data,
                                 uintptr_t data_len);

// # Safety
// - `init` has been called.
// - `floats` is valid for `floats_len` f32 reads.
// - Called from the same thread as `init`.
uint64_t processing_image_create_hdr(uint32_t width,
                                     uint32_t height,
                                     const float *floats,
                                     uintptr_t floats_len);

// Load an image from a file path.
//
// # Safety
// - Init has been called.
// - path is a valid null-terminated C string.
// - This is called from the same thread as init.
//
// Note: This function is currently synchronous but Bevy's asset loading is async.
// The image may not be immediately available. This needs to be improved.
uint64_t processing_image_load(const char *path);

void processing_image_resize(uint64_t image_id, uint32_t new_width, uint32_t new_height);

// Load pixels from an image into a caller-provided buffer.
//
// # Safety
// - Init and image_create have been called.
// - image_id is a valid ID returned from image_create.
// - buffer is a valid pointer to at least buffer_len Color elements.
// - buffer_len must equal width * height of the image.
// - This is called from the same thread as init.
void processing_image_readback(uint64_t image_id, struct Color *buffer, uintptr_t buffer_len);

// Load pixels from the graphics surface into a caller-provided buffer.
//
// # Safety
// - Init and graphics_create have been called.
// - graphics_id is a valid ID returned from graphics_create.
// - buffer is a valid pointer to at least buffer_len Color elements.
// - buffer_len must equal width * height of the graphics surface.
// - This is called from the same thread as init.
void processing_graphics_readback(uint64_t graphics_id, struct Color *buffer, uintptr_t buffer_len);

// Write a caller-provided pixel buffer back onto the graphics surface.
//
// # Safety
// - Init and graphics_create have been called.
// - graphics_id is a valid ID returned from graphics_create.
// - buffer is a valid pointer to at least buffer_len Color elements.
// - buffer_len must equal width * height of the graphics surface.
// - This is called from the same thread as init.
void processing_graphics_update(uint64_t graphics_id,
                                const struct Color *buffer,
                                uintptr_t buffer_len);

// Write a caller-provided pixel buffer onto a rectangular region of the surface.
//
// # Safety
// - Init and graphics_create have been called.
// - graphics_id is a valid ID returned from graphics_create.
// - buffer is a valid pointer to at least buffer_len Color elements.
// - buffer_len must equal width * height.
// - This is called from the same thread as init.
void processing_graphics_update_region(uint64_t graphics_id,
                                       uint32_t x,
                                       uint32_t y,
                                       uint32_t width,
                                       uint32_t height,
                                       const struct Color *buffer,
                                       uintptr_t buffer_len);

// Set a single pixel on the graphics surface.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_graphics_set(uint64_t graphics_id, uint32_t x, uint32_t y, struct Color color);

// Set the tint color applied to images.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_tint(uint64_t graphics_id, struct Color color);

// Remove the image tint.
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_no_tint(uint64_t graphics_id);

// Set how image() interprets its coordinates (CORNER/CORNERS/CENTER/RADIUS).
//
// SAFETY:
// - graphics_id is a valid ID returned from graphics_create.
// - This is called from the same thread as init.
void processing_image_mode(uint64_t graphics_id, uint8_t mode);

// Draw an image at (dx, dy) at its native size.
//
// SAFETY:
// - graphics_id and image_id are valid IDs from graphics_create/image_create.
// - This is called from the same thread as init.
void processing_image(uint64_t graphics_id, uint64_t image_id, float dx, float dy);

// Draw an image at (dx, dy) scaled to (d_width, d_height).
//
// SAFETY:
// - graphics_id and image_id are valid IDs from graphics_create/image_create.
// - This is called from the same thread as init.
void processing_image_scaled(uint64_t graphics_id,
                             uint64_t image_id,
                             float dx,
                             float dy,
                             float d_width,
                             float d_height);

// Draw the (sx, sy, s_width, s_height) source region of an image into the
// (dx, dy, d_width, d_height) destination rectangle.
//
// SAFETY:
// - graphics_id and image_id are valid IDs from graphics_create/image_create.
// - This is called from the same thread as init.
void processing_image_region(uint64_t graphics_id,
                             uint64_t image_id,
                             float dx,
                             float dy,
                             float d_width,
                             float d_height,
                             float sx,
                             float sy,
                             float s_width,
                             float s_height);

void processing_mode_3d(uint64_t graphics_id);

void processing_mode_2d(uint64_t graphics_id);

void processing_perspective(uint64_t graphics_id, float fov, float aspect, float near, float far);

void processing_ortho(uint64_t graphics_id,
                      float left,
                      float right,
                      float bottom,
                      float top,
                      float near,
                      float far);

void processing_transform_set_position(uint64_t entity_id, float x, float y, float z);

void processing_transform_translate(uint64_t entity_id, float x, float y, float z);

void processing_transform_set_rotation(uint64_t entity_id, float x, float y, float z);

void processing_transform_rotate_x(uint64_t entity_id, float angle);

void processing_transform_rotate_y(uint64_t entity_id, float angle);

void processing_transform_rotate_z(uint64_t entity_id, float angle);

void processing_transform_rotate_axis(uint64_t entity_id,
                                      float angle,
                                      float axis_x,
                                      float axis_y,
                                      float axis_z);

void processing_transform_set_scale(uint64_t entity_id, float x, float y, float z);

void processing_transform_scale(uint64_t entity_id, float x, float y, float z);

void processing_transform_look_at(uint64_t entity_id,
                                  float target_x,
                                  float target_y,
                                  float target_z);

void processing_transform_reset(uint64_t entity_id);

// Attach an orbit camera controller.
void processing_orbit_camera(uint64_t graphics_id);

// Attach a free-flight camera controller.
void processing_free_camera(uint64_t graphics_id);

// Attach a pan/zoom camera controller.
void processing_pan_camera(uint64_t graphics_id);

// Remove the active camera controller.
void processing_disable_camera_controller(uint64_t graphics_id);

// Set the camera distance from its center (zoom).
void processing_camera_set_distance(uint64_t graphics_id, float distance);

// Set the orbit camera's look-at center.
void processing_camera_set_center(uint64_t graphics_id, float x, float y, float z);

// Set the minimum camera distance.
void processing_camera_set_min_distance(uint64_t graphics_id, float min);

// Set the maximum camera distance.
void processing_camera_set_max_distance(uint64_t graphics_id, float max);

// Set the camera controller's sensitivity.
void processing_camera_set_speed(uint64_t graphics_id, float speed);

// Reset the camera controller to its initial pose.
void processing_camera_reset(uint64_t graphics_id);

// Position the camera at eye, looking at center with the given up.
//
// An active camera controller overrides this each frame.
void processing_camera(uint64_t graphics_id,
                       float eye_x,
                       float eye_y,
                       float eye_z,
                       float center_x,
                       float center_y,
                       float center_z,
                       float up_x,
                       float up_y,
                       float up_z);

// Right-multiply the model matrix by a column-major 4x4 matrix.
//
// # Safety
// - matrix points to at least 16 f32.
void processing_apply_matrix(uint64_t graphics_id, const float *matrix);

// The current model matrix, column-major. Flushes pending draws; identity on error.
struct Matrix processing_get_matrix(uint64_t graphics_id);

// Model-space point to world-space X (modelX).
float processing_model_x(uint64_t graphics_id, float x, float y, float z);

// Model-space point to world-space Y (modelY).
float processing_model_y(uint64_t graphics_id, float x, float y, float z);

// Model-space point to world-space Z (modelZ).
float processing_model_z(uint64_t graphics_id, float x, float y, float z);

// Model-space point to screen X in pixels (screenX).
float processing_screen_x(uint64_t graphics_id, float x, float y, float z);

// Model-space point to screen Y in pixels (screenY).
float processing_screen_y(uint64_t graphics_id, float x, float y, float z);

// Model-space point to screen depth in [0,1] (screenZ).
float processing_screen_z(uint64_t graphics_id, float x, float y, float z);

uint64_t processing_geometry_layout_create(void);

void processing_geometry_layout_add_position(uint64_t layout_id);

void processing_geometry_layout_add_normal(uint64_t layout_id);

void processing_geometry_layout_add_color(uint64_t layout_id);

void processing_geometry_layout_add_uv(uint64_t layout_id);

void processing_geometry_layout_add_attribute(uint64_t layout_id, uint64_t attr_id);

void processing_geometry_layout_destroy(uint64_t layout_id);

uint64_t processing_geometry_create_with_layout(uint64_t layout_id, uint8_t topology);

uint64_t processing_geometry_create(uint8_t topology);

void processing_geometry_normal(uint64_t geo_id, float nx, float ny, float nz);

void processing_geometry_color(uint64_t geo_id, float r, float g, float b, float a);

void processing_geometry_uv(uint64_t geo_id, float u, float v);

// # Safety
// - `name` must be a valid null-terminated C string.
uint64_t processing_geometry_attribute_create(const char *name, uint8_t format);

void processing_geometry_attribute_destroy(uint64_t attr_id);

uint64_t processing_geometry_attribute_position(void);

uint64_t processing_geometry_attribute_normal(void);

uint64_t processing_geometry_attribute_color(void);

uint64_t processing_geometry_attribute_uv(void);

uint64_t processing_geometry_attribute_rotation(void);

uint64_t processing_geometry_attribute_scale(void);

uint64_t processing_geometry_attribute_life(void);

uint64_t processing_geometry_attribute_velocity(void);

uint64_t processing_geometry_attribute_age(void);

uint8_t processing_geometry_attribute_format(uint64_t attr_id);

// # Safety
// - `out` is valid for `out_cap` byte writes (may be null when `out_cap == 0`
//   for a length query).
uint64_t processing_geometry_attribute_name(uint64_t attr_id, uint8_t *out, uint64_t out_cap);

void processing_geometry_attribute_float(uint64_t geo_id, uint64_t attr_id, float v);

void processing_geometry_attribute_float2(uint64_t geo_id, uint64_t attr_id, float x, float y);

void processing_geometry_attribute_float3(uint64_t geo_id,
                                          uint64_t attr_id,
                                          float x,
                                          float y,
                                          float z);

void processing_geometry_attribute_float4(uint64_t geo_id,
                                          uint64_t attr_id,
                                          float x,
                                          float y,
                                          float z,
                                          float w);

void processing_geometry_vertex(uint64_t geo_id, float x, float y, float z);

void processing_geometry_index(uint64_t geo_id, uint32_t i);

uint32_t processing_geometry_vertex_count(uint64_t geo_id);

uint32_t processing_geometry_index_count(uint64_t geo_id);

// # Safety
// - `out` must be valid for writes of `out_len` elements.
uint32_t processing_geometry_get_positions(uint64_t geo_id,
                                           uint32_t start,
                                           uint32_t end,
                                           float (*out)[3],
                                           uint32_t out_len);

// # Safety
// - `out` must be valid for writes of `out_len` elements.
uint32_t processing_geometry_get_normals(uint64_t geo_id,
                                         uint32_t start,
                                         uint32_t end,
                                         float (*out)[3],
                                         uint32_t out_len);

// # Safety
// - `out` must be valid for writes of `out_len` elements.
uint32_t processing_geometry_get_colors(uint64_t geo_id,
                                        uint32_t start,
                                        uint32_t end,
                                        float (*out)[4],
                                        uint32_t out_len);

// # Safety
// - `out` must be valid for writes of `out_len` elements.
uint32_t processing_geometry_get_uvs(uint64_t geo_id,
                                     uint32_t start,
                                     uint32_t end,
                                     float (*out)[2],
                                     uint32_t out_len);

// # Safety
// - `out` must be valid for writes of `out_len` elements.
uint32_t processing_geometry_get_indices(uint64_t geo_id,
                                         uint32_t start,
                                         uint32_t end,
                                         uint32_t *out,
                                         uint32_t out_len);

void processing_geometry_set_vertex(uint64_t geo_id, uint32_t index, float x, float y, float z);

void processing_geometry_set_normal(uint64_t geo_id, uint32_t index, float nx, float ny, float nz);

void processing_geometry_set_color(uint64_t geo_id,
                                   uint32_t index,
                                   float r,
                                   float g,
                                   float b,
                                   float a);

void processing_geometry_set_uv(uint64_t geo_id, uint32_t index, float u, float v);

void processing_geometry_destroy(uint64_t geo_id);

void processing_model(uint64_t graphics_id, uint64_t geo_id);

uint64_t processing_geometry_box(float width, float height, float depth);

uint64_t processing_geometry_sphere(float radius, uint32_t sectors, uint32_t stacks);

uint64_t processing_light_create_directional(uint64_t graphics_id,
                                             struct Color color,
                                             float illuminance);

uint64_t processing_light_create_point(uint64_t graphics_id,
                                       struct Color color,
                                       float intensity,
                                       float range,
                                       float radius);

uint64_t processing_light_create_spot(uint64_t graphics_id,
                                      struct Color color,
                                      float intensity,
                                      float range,
                                      float radius,
                                      float inner_angle,
                                      float outer_angle);

uint64_t processing_material_create_pbr(void);

uint64_t processing_material_create_custom(uint64_t shader_id);

// Set a float field on a material.
//
// # Safety
// - `name` is a valid null-terminated C string.
void processing_material_set_float(uint64_t mat_id, const char *name, float value);

// Set a float4 field on a material.
//
// # Safety
// - `name` is a valid null-terminated C string.
void processing_material_set_float4(uint64_t mat_id,
                                    const char *name,
                                    float r,
                                    float g,
                                    float b,
                                    float a);

void processing_material_destroy(uint64_t mat_id);

void processing_material(uint64_t window_id, uint64_t mat_id);

void processing_material_set_alpha_mode(uint64_t mat_id, uint8_t mode, float cutoff);

void processing_material_set_double_sided(uint64_t mat_id, bool value);

void processing_material_set_unlit(uint64_t mat_id, bool value);

void processing_material_set_depth_write(uint64_t mat_id, bool value);

void processing_material_set_custom_blend_mode(uint64_t mat_id,
                                               uint8_t color_src,
                                               uint8_t color_dst,
                                               uint8_t color_op,
                                               uint8_t alpha_src,
                                               uint8_t alpha_dst,
                                               uint8_t alpha_op);

void processing_graphics_apply_filter(uint64_t graphics_id, uint64_t filter_id);

uint64_t processing_filter_create(uint64_t shader_id);

void processing_filter_destroy(uint64_t filter_id);

void processing_filter_set_passes(uint64_t filter_id, uint32_t passes);

uint64_t processing_filter_blur(void);

uint64_t processing_filter_invert(void);

uint64_t processing_filter_gray(void);

uint64_t processing_filter_threshold(void);

uint64_t processing_filter_posterize(void);

uint64_t processing_filter_opaque(void);

uint64_t processing_filter_erode(void);

uint64_t processing_filter_dilate(void);

// Create a shader from WGSL source.
//
// # Safety
// - `source` is a valid null-terminated C string.
uint64_t processing_shader_create(const char *source);

// # Safety
// - `path` is a valid null-terminated C string.
uint64_t processing_shader_load(const char *path);

void processing_shader_destroy(uint64_t shader_id);

uint64_t processing_buffer_create(uint64_t size);

// # Safety
// - `data` is valid for `len` byte reads.
uint64_t processing_buffer_create_with_data(const uint8_t *data, uint64_t len);

// # Safety
// - `data` is valid for `len` byte reads.
void processing_buffer_write(uint64_t buf_id, const uint8_t *data, uint64_t len);

// Returns the byte length of a buffer, or 0 if not found (error is set).
uint64_t processing_buffer_size(uint64_t buf_id);

// Read buffer contents into `out`. Returns the buffer's byte length;
// `out` is only written when it fits in `out_len`. Pass `out_len == 0` for a
// size query.
//
// # Safety
// - `out` is valid for `out_len` byte writes (may be null when `out_len == 0`).
uint64_t processing_buffer_read(uint64_t buf_id, uint8_t *out, uint64_t out_len);

void processing_buffer_destroy(uint64_t buf_id);

uint64_t processing_compute_create(uint64_t shader_id);

// # Safety
// - `name` must be non-null.
void processing_shader_set_float(uint64_t entity, const char *name, float value);

// # Safety
// - `name` must be non-null.
void processing_shader_set_int(uint64_t entity, const char *name, int32_t value);

// # Safety
// - `name` must be non-null.
void processing_shader_set_uint(uint64_t entity, const char *name, uint32_t value);

// # Safety
// - `name` must be non-null.
void processing_shader_set_vec2(uint64_t entity, const char *name, float x, float y);

// # Safety
// - `name` must be non-null.
void processing_shader_set_vec3(uint64_t entity, const char *name, float x, float y, float z);

// # Safety
// - `name` must be non-null.
void processing_shader_set_vec4(uint64_t entity,
                                const char *name,
                                float x,
                                float y,
                                float z,
                                float w);

// # Safety
// - `name` must be non-null.
void processing_shader_set_ivec2(uint64_t entity, const char *name, int32_t x, int32_t y);

// # Safety
// - `name` must be non-null.
void processing_shader_set_ivec3(uint64_t entity,
                                 const char *name,
                                 int32_t x,
                                 int32_t y,
                                 int32_t z);

// # Safety
// - `name` must be non-null.
void processing_shader_set_ivec4(uint64_t entity,
                                 const char *name,
                                 int32_t x,
                                 int32_t y,
                                 int32_t z,
                                 int32_t w);

// # Safety
// - `name` must be non-null.
void processing_shader_set_uvec2(uint64_t entity, const char *name, uint32_t x, uint32_t y);

// # Safety
// - `name` must be non-null.
void processing_shader_set_uvec3(uint64_t entity,
                                 const char *name,
                                 uint32_t x,
                                 uint32_t y,
                                 uint32_t z);

// # Safety
// - `name` must be non-null.
void processing_shader_set_uvec4(uint64_t entity,
                                 const char *name,
                                 uint32_t x,
                                 uint32_t y,
                                 uint32_t z,
                                 uint32_t w);

// # Safety
// - `name` must be non-null.
// - `value` must point to at least 16 f32 elements (column-major).
void processing_shader_set_mat4(uint64_t entity, const char *name, const float *value);

// # Safety
// - `name` must be non-null.
void processing_shader_set_texture(uint64_t entity, const char *name, uint64_t image_id);

// # Safety
// - `name` must be non-null.
void processing_shader_set_buffer(uint64_t entity, const char *name, uint64_t buf_id);

// Binds `{name}_offsets`, `{name}_sorted` and the `{name}` uniform.
//
// # Safety
// - `name` must be non-null.
void processing_shader_set_grid(uint64_t entity, const char *name, uint64_t grid_id);

void processing_compute_dispatch(uint64_t compute_id, uint32_t x, uint32_t y, uint32_t z);

void processing_compute_destroy(uint64_t compute_id);

// # Safety
// - `attr_ids` is valid for `attr_count` u64 reads.
uint64_t processing_particles_create(uint32_t capacity,
                                     const uint64_t *attr_ids,
                                     uint32_t attr_count);

// # Safety
// - `attr_ids` is valid for `attr_count` u64 reads.
uint64_t processing_particles_create_from_geometry(uint64_t geo_id,
                                                   const uint64_t *attr_ids,
                                                   uint32_t attr_count);

void processing_particles_destroy(uint64_t particles_id);

uint32_t processing_particles_capacity(uint64_t particles_id);

uint64_t processing_particles_buffer(uint64_t particles_id, uint64_t attr_id);

// # Safety
// - `attr_ids` is valid for `attr_count` u64 reads.
// - `attr_byte_lengths` is valid for `attr_count` u64 reads.
// - `data` is valid for `sum(attr_byte_lengths)` byte reads.
void processing_particles_emit(uint64_t particles_id,
                               uint32_t n,
                               const uint64_t *attr_ids,
                               const uint8_t *data,
                               const uint64_t *attr_byte_lengths,
                               uint32_t attr_count);

void processing_particles_emit_gpu(uint64_t particles_id, uint32_t n, uint64_t compute_id);

uint64_t processing_particles_kernel_noise(void);

uint64_t processing_particles_kernel_transform(void);

uint64_t processing_particles_kernel_attract(void);

uint64_t processing_particles_kernel_drag(void);

uint64_t processing_particles_kernel_vortex(void);

int32_t processing_particles_attribute_add(uint64_t particles_id, uint64_t attribute_id);

uint64_t processing_particles_kernel_force(void);

uint64_t processing_particles_kernel_integrate(void);

uint64_t processing_particles_kernel_age(void);

uint64_t processing_particles_kernel_bounds_sphere(void);

uint64_t processing_particles_kernel_bounds_box(void);

uint64_t processing_particles_kernel_bounds_geometry(uint64_t geometry_entity);

uint64_t processing_particles_kernel_impulse(void);

uint64_t processing_particles_kernel_orient(void);

uint64_t processing_particles_kernel_field(void);

uint64_t processing_particles_kernel_attr_linear(void);

uint64_t processing_particles_kernel_attr_combine(void);

uint64_t processing_particles_kernel_attr_mix(void);

uint64_t processing_particles_kernel_attr_lookup1d(void);

uint64_t processing_particles_kernel_attr_lookup2d(void);

uint64_t processing_particles_scatter_create(uint64_t geometry_id);

uint64_t processing_particles_scatter_volume_create(uint64_t geometry_id);

// # Safety
// - `path` is a valid null-terminated C string.
uint64_t processing_gltf_load(uint64_t graphics_id, const char *path);

// # Safety
// - `name` is a valid null-terminated C string.
uint64_t processing_gltf_geometry(uint64_t gltf_id, const char *name);

// # Safety
// - `name` is a valid null-terminated C string.
uint64_t processing_gltf_material(uint64_t gltf_id, const char *name);

void processing_gltf_camera(uint64_t gltf_id, uint32_t index);

uint64_t processing_gltf_light(uint64_t gltf_id, uint32_t index);

void processing_particles_apply(uint64_t particles_id, uint64_t compute_id);

// Returns the grid id, or 0 on error.
uint64_t processing_particles_grid_create(uint64_t particles_id,
                                          float min_x,
                                          float min_y,
                                          float min_z,
                                          float cell_size,
                                          uint32_t dims_x,
                                          uint32_t dims_y,
                                          uint32_t dims_z);

void processing_particles_grid_build(uint64_t grid_id, uint64_t position_buf_id);

void processing_particles_grid_destroy(uint64_t grid_id);

// Writes each particle's `neighbors` and `neighbor_count`, rebuilding the grid first.
void processing_particles_find_neighbors(uint64_t particles_id,
                                         uint64_t grid_id,
                                         float radius,
                                         uint32_t max);

void processing_particles_draw(uint64_t graphics_id, uint64_t particles_id, uint64_t geometry_id);

void processing_fill_buffer(uint64_t graphics_id, uint64_t buffer_id);

void processing_material_set_albedo_buffer(uint64_t mat_id, uint64_t buffer_id);

void processing_material_set_emissive_buffer(uint64_t mat_id, uint64_t buffer_id);

// # Safety
// - `out_x`, `out_y`, `out_z` are each valid for one f32 write.
void processing_graphics_world_from_screen(uint64_t graphics_id,
                                           float sx,
                                           float sy,
                                           float depth,
                                           float *out_x,
                                           float *out_y,
                                           float *out_z);

void processing_graphics_set_bloom(uint64_t graphics_id, float intensity, float threshold);

void processing_graphics_remove_bloom(uint64_t graphics_id);

void processing_graphics_tonemapping(uint64_t graphics_id, uint8_t mode);

void processing_graphics_no_tonemapping(uint64_t graphics_id);

void processing_input_mouse_move(uint64_t surface_id, float x, float y);

void processing_input_mouse_button(uint64_t surface_id, uint8_t button, bool pressed);

void processing_input_scroll(uint64_t surface_id, float x, float y);

void processing_input_key(uint64_t surface_id, uint32_t key_code, bool pressed);

void processing_input_char(uint64_t surface_id, uint32_t key_code, uint32_t codepoint);

void processing_input_cursor_enter(uint64_t surface_id);

void processing_input_cursor_leave(uint64_t surface_id);

void processing_input_focus(uint64_t surface_id, bool focused);

// Show the mouse cursor with the given system type (PROCESSING_CURSOR_*).
void processing_cursor(uint64_t surface_id, uint8_t kind);

// Hide the mouse cursor.
void processing_no_cursor(uint64_t surface_id);

void processing_input_flush(void);

float processing_mouse_x(uint64_t surface_id);

float processing_mouse_y(uint64_t surface_id);

float processing_pmouse_x(uint64_t surface_id);

float processing_pmouse_y(uint64_t surface_id);

bool processing_mouse_is_pressed(void);

int8_t processing_mouse_button(void);

bool processing_key_is_pressed(void);

bool processing_key_is_down(uint32_t key_code);

bool processing_key_just_pressed(uint32_t key_code);

uint32_t processing_key(void);

uint32_t processing_key_code(void);

float processing_moved_x(void);

float processing_moved_y(void);

float processing_mouse_wheel(void);

// Check if the last operation resulted in an error. Returns a pointer to an error message, or null
// if there was no error.
const char *processing_check_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PROCESSING_H */
